export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const GET_SPACEX_DATA_SUCCESS = 'GET_SPACEX_DATA_SUCCESS';
export const GET_SPACEX_DATA_FAILURE = 'GET_SPACEX_DATA_FAILURE';
